root_finder: Bisection.c Newtons.c Secant.c
	gcc -Wall -ansi -static -ggdb -c Bisection.c Newtons.c Secant.c
	gcc -o Bisection Bisection.o -lm
	gcc -o Newtons Newtons.o -lm
	gcc -o Secant Secant.o -lm
	rm *.o
